### ISSUE TITLE
Coupled Models Failing in Docker  badlands-dev

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/UWGeodynamics#119]
i can my wedge and T11 today with the badlands-dev docker they fail
```python-error
An uncaught exception was encountered on processor 0.
Traceback (most recent call last):
  File "t11.py", line 137, in <module>
    Model.run_for(5.0 * u.megayear, checkpoint_interval=0.01*u.megayear)
  File "/usr/local/lib/python3.5/dist-packages/pint/registry_helpers.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1642, in run_for
    self._update()
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1753, in _update
    self.surfaceProcesses.solve(dt)
  File "/opt/UWGeodynamics/UWGeodynamics/surfaceProcesses.py", line 215, in solve
    self.badlands_model.run_to_time(self.time_years + dt_years)
  File "/opt/pyBadlands_serial/pyBadlands/model.py", line 283, in run_to_time
    self.inIDs, True, self.strata.xyi, self.strata.ids)
  File "/opt/pyBadlands_serial/pyBadlands/forcing/forceSim.py", line 586, in load_Disp_map
    if self.time3d > 0. and (self.injected_disps is not None or self.Map_disp[event] != None):
TypeError: unorderable types: NoneType() > float()
application called MPI_Abort(comm=0x84000004, 1) - process 0
```

**Comment by rbeucher** [comment]
Ok I have fixed this. Docker image is rebuilding...

**Comment by arijitlaik** [comment]
cool. thanks, :) closing this

**Comment by arijitlaik** [comment]
could you please trigger a build for the badlands-dev docker file?

**Comment by arijitlaik** [comment]
i just tried a now with badlands-dev , its still not working,
sorry to bother you

**Comment by rbeucher** [comment]
same issue?

**Comment by rbeucher** [comment]
OK I was pulling the python3 branch, I changed that

**Comment by arijitlaik** [comment]
thanks, waiting for the image to build, will close it then :)

**Comment by arijitlaik** [comment]
uw dev doesn't have python2, so this is an issue, and pip3 installation of badlands fails
```
  warnings.warn("The unit of the quantity is stripped.", UnitStrippedWarning)
An uncaught exception was encountered on processor 2.
Traceback (most recent call last):
  File "/opt/UWGeodynamics/UWGeodynamics/surfaceProcesses.py", line 56, in __init__
    import pyBadlands
  File "/opt/pyBadlands_serial/pyBadlands/__init__.py", line 35, in <module>
    from .simulation import buildFlux
  File "/opt/pyBadlands_serial/pyBadlands/simulation/buildFlux.py", line 17, in <module>
    from buildMesh import _get_reference_elevation
ImportError: No module named 'buildMesh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wedge.py", line 204, in <module>
    aspectRatio2d=0.2,
  File "/opt/UWGeodynamics/UWGeodynamics/surfaceProcesses.py", line 61, in __init__
    variables""")
ImportError: pyBadlands import as failed. Please check your
                              installation, PYTHONPATH and PATH environment
                              variables
application called MPI_Abort(comm=0x84000002, 1) - process 2

```

**Comment by rbeucher** [comment]
OK I'm on it sorry.

**Comment by rbeucher** [comment]
Actually, have you tried the uwgeodynamics:dev image? It has pyBadlands, I was planning to deprecate the badlands-dev

**Comment by arijitlaik** [comment]
oh, ill just tryout in a while and let you know

**Comment by arijitlaik** [comment]
no ;/ 
```
WeightsCalculator_CalculateAll(): finished update of weights for swarm "7DIE0X1W__swarm"
Running with UWGeodynamics version 2.8.1-dev-7d4da76(development)

Non linear solver - iteration 3
Linear solver (AMSVH2WB__system-execute) 

BSSCR -- Block Stokes Schur Compliment Reduction Solver 


-----  K2_GMG  ------

AUGMENTED LAGRANGIAN K2 METHOD - Penalty = 1000000.000000


	* K+p*K2 in time: 0.025393 seconds

  Setting schur_pc to "gkgdiag" 


SCR Solver Summary:

  RHS V Solve:            = 0.01812 secs / 1 its
  Pressure Solve:         = 0.09502 secs / 5 its
  Final V Solve:          = 0.01672 secs / 1 its

  Total BSSCR Linear solve time: 0.879174 seconds

Linear solver (AMSVH2WB__system-execute), solution time 8.866572e-01 (secs)
In func SystemLinearEquations_NonLinearExecute: Iteration 3 of 500 - Residual 0.0066088 - Tolerance = 0.01
Non linear solver - Residual 6.60881503e-03; Tolerance 1.0000e-02 - Converged - 7.000287e+00 (secs)

In func SystemLinearEquations_NonLinearExecute: Converged after 3 iterations.
Time Integration
	2nd order:                 N5NXSTTN__integrand -    0.2467 [min] /    0.4709 [max] (secs)
Time Integration - 0.246665 [min] / 0.47142 [max] (secs)
In func WeightsCalculator_CalculateAll(): for swarm "7DIE0X1W__swarm"
	done 33% (3648 cells)...
	done 67% (7296 cells)...
	done 100% (10944 cells)...
WeightsCalculator_CalculateAll(): finished update of weights for swarm "7DIE0X1W__swarm"
Options:  -change_backsolve False -force_correction True -Q22_pc_type gkgdiag -restore_K False -ksp_type bsscr -remove_constant_pressure_null_space False -rescale_equations False -change_A11rhspresolve False -pc_type none -ksp_k2_type NULL -A11_pc_factor_mat_solver_package mumps -A11_pc_type lu -A11_ksp_type preonly -scr_ksp_type fgmres -scr_ksp_rtol 1e-05 -A11_mg_active False
Processing surface with Badlands
/opt/UWGeodynamics/UWGeodynamics/__init__.py:83: UserWarning: 'Dimensionalize' has been changed to 'dimensionalise', please use the later
  warnings.warn("""'Dimensionalize' has been changed to 'dimensionalise', please use the later""")
/usr/local/lib/python3.5/dist-packages/pint/quantity.py:1377: UnitStrippedWarning: The unit of the quantity is stripped.
  warnings.warn("The unit of the quantity is stripped.", UnitStrippedWarning)
An uncaught exception was encountered on processor 0.
Traceback (most recent call last):
  File "wedge.py", line 218, in <module>
    10 * u.megayears, checkpoint_interval=0.01 * u.megayears, restartStep=None
  File "/usr/local/lib/python3.5/dist-packages/pint/registry_helpers.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1643, in run_for
    self._update()
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1755, in _update
    self.surfaceProcesses.solve(dt)
  File "/opt/UWGeodynamics/UWGeodynamics/surfaceProcesses.py", line 215, in solve
    self.badlands_model.run_to_time(self.time_years + dt_years)
  File "/opt/pyBadlands_serial/pyBadlands/model.py", line 278, in run_to_time
    updateMesh = self.force.load_Disp_map(self.tNow, self.FVmesh.node_coords[:, :2], self.inIDs)
  File "/opt/pyBadlands_serial/pyBadlands/forcing/forceSim.py", line 586, in load_Disp_map
    if self.time3d > 0. and (self.injected_disps is not None or self.Map_disp[event] != None):
TypeError: unorderable types: NoneType() > float()
application called MPI_Abort(comm=0x84000004, 1) - process 0

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 30 RUNNING AT 7f20d8a4e3e3
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================

```

**Comment by arijitlaik** [comment]
i have a old docker image which i build on March 28, 2019 05:40 AM , it works fine there 
https://hub.docker.com/r/arijitlaik/uwgeobadlands

**Comment by rbeucher** [comment]
Ok I need to rebuild it

**Comment by rbeucher** [comment]
pyBadlands is now py3 compatible but there are still a few things that need fixing apparently

**Comment by arijitlaik** [comment]
closing this.

**Comment by bknight1** [comment]
Hi @rbeucher and @arijitlaik did this get fixed? I've run into the same issue:

```
Processing surface with Badlands
/usr/local/lib/python3.5/dist-packages/pint/quantity.py:1377: UnitStrippedWarning: The unit of the quantity is stripped.
  warnings.warn("The unit of the quantity is stripped.", UnitStrippedWarning)
Traceback (most recent call last):
  File "BadlandsE-WQ_06Nov19-25km_CT-2-LR.py", line 970, in <module>
    Model.run_for(Total_Time * u.megayears, checkpoint_interval=The_Checkpoint_interval*u.megayears)
  File "/usr/local/lib/python3.5/dist-packages/pint/registry_helpers.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/UWGeodynamics/_model.py", line 1634, in run_for
    self._update()
  File "/usr/local/lib/python3.5/dist-packages/UWGeodynamics/_model.py", line 1748, in _update
    self.surfaceProcesses.solve(dt)
  File "/usr/local/lib/python3.5/dist-packages/UWGeodynamics/surfaceProcesses.py", line 215, in solve
    self.badlands_model.run_to_time(self.time_years + dt_years)
  File "/opt/pyBadlands/pyBadlands/model.py", line 318, in run_to_time
    if self.input.erolays >= 0:
TypeError: unorderable types: NoneType() >= int()
```

Cheers
